# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targets.Target', verbose_name='Глобальная цель'),
        ),
    ]
