# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.PositiveIntegerField(choices=[('Проект', 1), ('Навык', 2)], default=1, verbose_name='Тип цели'),
        ),
    ]
