# Generated by Django 2.0 on 2018-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_target_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.PositiveIntegerField(choices=[(1, 'Проект'), (2, 'Навык')], default=1, verbose_name='Тип цели'),
        ),
    ]
